geekshop/authapp/urls.py
from django.conf.urls import url
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url(r'^login/', authapp.login, name= 'login'),
    url(r'^logout/', authapp.logout, name= 'logout'),
    url(r'^register/', authapp.register, name='register'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import mainapp.views as mainapp
import authapp.views as authapp


urlpatterns = [
    url(r'^$', mainapp.main, name='main'),
    url(r'^auth/', include('authapp.urls', namespace= 'auth')),
    url(r'^products/', include('mainapp.urls' , namespace= 'products')),
    url(r'^contacts/$', mainapp.contacts, name='contacts'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.conf.urls import url
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    url('^$', mainapp.products, name='index'),
    url(r'^(?P<pk>\d+)/$', mainapp.products, name='product'),
]

geekshop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class ShopUser(AbstractUser):
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name = 'возраст')

geekshop/mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name='имя категории', max_length= 128, unique= True)
    description = models.TextField(verbose_name='описание категории', max_length= 500, blank= True)

    def __str__(self):
        return self.name

class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length= 128)
    image = models.ImageField(upload_to='products_images', blank= True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length= 60, blank= True)
    description = models.TextField(verbose_name='описание продукта', blank= True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits= 8, decimal_places= 2, default= 0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default= 0)

    def __str__(self):
        return f"{self.name} ({self.category})"

geekshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from .models import ShopUser

class ShopUserLoginForm(AuthenticationForm):
    class Meta :
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta :
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

geekshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from mainapp.forms import ShopUserLoginForm, ShopUserRegisterForm
from django.contrib import auth
from django.urls import reverse

def register (request):
    title = 'регистрация'

    if request.method == 'POST' :
        register_form = ShopUserRegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse( 'auth:login' ))
    else :
        register_form = ShopUserRegisterForm()

    content = { 'title' : title, 'register_form' : register_form}
    return render(request, 'authapp/register.html' , content)

def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))

geekshop/mainapp/views.py
from django.shortcuts import render
from .models import Product

def main (request):
    product_list = Product.objects.all()

    return render(request, 'mainapp/index.html', context={'user': request.user, 'products': product_list})

def products (request, pk=None):
    print(pk)
    return render(request, 'mainapp/products.html')

def contacts (request):
    return render(request, 'mainapp/contacts.html')

geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset = "utf-8">
    <title>
    {% block title %}
        {{ title|title }}
    {% endblock %}
    </title>
    {% block css %}
        <link rel = "stylesheet" type = "text/css" href = "{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
    <div class = "container">
        <div class = "login">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class = "form-horizontal" method = "post">
        {% csrf_token %}
        {{ login_form.as_p }}
<!--        <input name="username">-->
<!--        <input name="password" type="password">-->
        <br>
        <input class = "form-control" type = "submit" value = "войти">
    </form>
{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class = "form-horizontal" method = "post">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class = "form-control" type = "submit" value = "зарегистрироваться">
    </form>
{% endblock %}

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        {{ title|title }}
    {% endblock %}

    {% block css %}
        <link rel = "stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
</head>
<body>
    <div class = "container">
        {% block menu %}
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
    {% block footer %}
        <div class = "footer">
            <div class = "text-footer">
                <h3>Контакты</h3>
            </div>
            <div class = "text-footer">
                <h3>Полезная информация</h3>
            </div>
        </div>
    {% endblock %}
</body>
</html>

geekshop/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
    <title>Контакты</title>
{% endblock %}
{% block content %}
    {% include 'mainapp/includes/inc_menu.html' %}
    <h1>Контакты</h1>
    {% now "d.m.Y" %}
    <br>
    <img src="{% static 'img/paradise.jpg' %}">
{% endblock %}

geekshop/mainapp/templates/mainapp/includes/inc_menu.html
<ul class = "menu">
    <li><a class = "{% if request.resolver_match.url_name == 'main' %}
                        active
                    {% endif %}" href = "{% url 'main' %}">Главная</a></li>
    <li><a class = "{% if request.resolver_match.namespace == 'products' %}
                        active
                    {% endif %}" href = "{% url 'products:index' %}">Продукты</a></li>
    <li><a class = "{% if request.resolver_match.url_name == 'contacts' %}
                        active
                    {% endif %}" href = "{% url 'contacts' %}" >Контакты</a></li>
</ul>

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Главная</title>
{% endblock %}
{% block content %}
    {% include 'mainapp/includes/inc_menu.html' %}
    {% if user.is_authenticated %}
        <h1>{{ user.username|title }}</h1>
        <a href = "{% url 'auth:logout' %}">Выйдите</a>
    {% else %}
        <a href = "{% url 'auth:login' %}">Войдите</a> или <a href = "{% url 'auth:login' %}">Зарегистрируйтесь</a>
    {% endif %}
    <h1 class="main">Главная</h1>
    <ul>
        {% for product in products %}
            <li>{{ product.name }} ({{ product.category }})</li>
        {% endfor %}
    </ul>
    {{ user.name|title }} {{ user.surname|title }}
    {% now "d.m.Y" %}
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Продукты</title>
{% endblock %}
{% block content %}
    {% include 'mainapp/includes/inc_menu.html' %}
    <h1>Продукты</h1>
    {% now "d.m.Y" %}
{% endblock %}